### ISSUE TITLE
Works on Mac, fails on Linux (Ubuntu 14.04)

### ISSUE THREAD

**Issue by sergey-a-berezin** [sergey-a-berezin/acme-tiny-cron#8]
I developed the script on a Mac and it worked just fine, tests and all.

However, on Ubuntu I get the following error:

Traceback (most recent call last):
  File "/usr/lib/python3.4/unittest/mock.py", line 1136, in patched
    return func(*args, **keywargs)
  File "acme_tiny_cron/cron_test.py", line 268, in test_process_certs_up_to_date
    get_domain_text(cert_path=self.cert_file, mode='STAGING'),
  File "acme_tiny_cron/cron_test.py", line 81, in get_config_proto
    protobuf.text_format.Merge(config_text, config)
AttributeError: 'module' object has no attribute 'text_format'
